// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransformSsbBlobToSQL.Data;

namespace TransformSsbBlobToSQL.Migrations
{
    [DbContext(typeof(SsbContext))]
    [Migration("20210629101824_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("TransformSsbBlobToSQL.Models.Ssb07849", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Antall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biltype")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Drivstofftype")
                        .HasColumnType("TEXT");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeKjøring")
                        .HasColumnType("TEXT");

                    b.Property<int>("År")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ssb07849s");
                });
#pragma warning restore 612, 618
        }
    }
}
